from app.models import db, Player, Tour, Result, Opponent
from app import app
import datetime

# pipenv shell
# flask run


first = datetime.datetime(2023, 9, 11)
second = datetime.datetime(2023, 9, 12)
third = datetime.datetime(2023, 9, 14)
fourth = datetime.datetime(2023, 9, 15)
fifth = datetime.datetime(2023, 9, 16)
sixth = datetime.datetime(2023, 9, 17)
seventh = datetime.datetime(2023, 9, 18)

# ../static/images/
with app.app_context():

    # opp0 = Opponent(player_id=4, opponent_id=20,victory=True,tour_name=2)
    # opp2 = Opponent(player_id=4, opponent_id=63,victory=True,tour_name=3)
    # opp3 = Opponent(player_id=4, opponent_id=34,victory=False,tour_name=6)
    # opp4 = Opponent(player_id=4, opponent_id=25,victory=True,tour_name=7)

    # res0 = Result(first='obito.webp', second='gaara.jpeg', third='madara.gif', fourth='jiraiya.jpeg', fifth='kaguya.jpeg', sixth='minato.jpeg', seventh='chakra.jpeg', eigth='orochimaru.jpeg', ninth='warsakura.jpeg', tenth='shikamaru.jpeg')
    # res2 = Result(first='anbu_kakashi.webp', second='six-paths-sage.jpeg', third='amaterasu.jpeg', fourth='pain.webp', fifth='gaara.jpeg', sixth='killer_bee.jpeg', seventh='sage.gif', eigth='kaguya.jpeg', ninth='anbu-itachi.jpeg', tenth='shuriken.jpeg')
    # res3 = Result(first='anbu-itachi.jpeg', second='gaara.jpeg', third='hinata.jpeg', fourth='yamato.webp', fifth='hashirama.webp', sixth='tobirama.webp', seventh='chakra.jpeg', eigth='madara.gif', ninth='sage.gif', tenth='kankuro.jpeg')
    # res4 = Result(first='neji.jpeg', second='regkak.jpeg', third='akat-sas.jpeg', fourth='minato.jpeg', fifth='kankuro.jpeg', sixth='konan.jpeg', seventh='itachi.jpeg', eigth='anbu_kakashi.webp', ninth='kurama.jpeg', tenth='sage.gif')
    # res5 = Result(first='madara.gif', second='gaara.jpeg', third='asuma.jpeg', fourth='tobirama.webp', fifth='temari.webp', sixth='amaterasu.jpeg', seventh='anbu_kakashi.webp', eigth='minato.jpeg', ninth='kurama.jpeg', tenth='sword.jpeg')

    tour0 = Tour(link = 'https://challonge.com/uzux80ch', name='1st Battle Royale', date=first, first='obito.webp', second='gaara.jpeg', third='madara.gif')
    tour2 = Tour(link = 'https://challonge.com/ptivmhqc', name='2nd Battle Royale', date=second, first='anbu_kakashi.webp', second='six-paths-sage.jpeg', third='amaterasu.jpeg')
    tour3 = Tour(link = 'https://challonge.com/42o6doy3', name='3rd Battle Royale', date=third, first='anbu-itachi.jpeg', second='gaara.jpeg', third='hinata.jpeg')
    tour4 = Tour(link = 'https://challonge.com/ez389kce', name='4th Battle Royale', date=fourth, first='neji.jpeg', second='regkak.jpeg', third='akat-sas.jpeg')
    tour5 = Tour(link = 'https://challonge.com/vvvuedo', name='5th Battle Royale', date=fifth, first='madara.gif', second='gaara.jpeg', third='asuma.jpeg')
    tour6 = Tour(link = 'https://challonge.com/h0fbyqgx', name='6th Battle Royale', date=sixth, first='juubito.jpeg', second='six-paths-sage.jpeg', third='kaguya.jpeg')
    tour7 = Tour(link = 'https://challonge.com/zsnukbwc', name='7th Battle Royale', date=seventh, first='regkak.jpeg', second='regsas.jpeg', third='juubito.jpeg')



    player1 = Player(name='Akatsuki Sasuke',team='Penn State', logo='https://gopsusports.com/_nuxt/logo-BDHEpLK6.svg',  wins=0, loss=0, points=0, img='../static/images/akat-sas.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player2 = Player(name='Amaterasu Sasuke', team = 'Ok State', logo='https://gopsusports.com/_nuxt/logo-BDHEpLK6.svg', wins=0, loss=0, points=0, img='../static/images/amaterasu.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player3 = Player(name='Anbu Itachi', wins=0, loss=0, points=0, img='../static/images/anbu-itachi.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player4 = Player(name='Anbu Kakashi',wins=0, loss=0, points=0, img='../static/images/anbu_kakashi.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player5 = Player(name='Asuma', wins=0, loss=0, points=0,img='../static/images/asuma.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player6 = Player(name='Beat Sasuke', wins=0, loss=0, points=0, img='../static/images/beat-sas.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player7 = Player(name='Beat Naruto', wins=0, loss=0, points=0, img='../static/images/beat-nar.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player8 = Player(name='Chakra Naruto', wins=0, loss=0, points=0, img='../static/images/chakra.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player9 = Player(name='Choji', wins=0, loss=0, points=0, img='../static/images/choji.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player10 = Player(name='Cursed Hidan', wins=0, loss=0, points=0, img='../static/images/cursed.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player11 = Player(name='Dadara', wins=0, loss=0, points=0, img='../static/images/dadara.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player12 = Player(name='Deidara', wins=0, loss=0, points=0, img='../static/images/deidara.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player13 = Player(name='Gaara', wins=0, loss=0, points=0, img='../static/images/gaara.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player14 = Player(name='Gamabunta', wins=0, loss=0, points=0, img='../static/images/bunta.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player15 = Player(name='Gamakichi', wins=0, loss=0, points=0, img='../static/images/kichi.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player16 = Player(name='Hashirama', wins=0, loss=0, points=0, img='../static/images/hashirama.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player17 = Player(name='Hiroku', wins=0, loss=0, points=0, img='../static/images/hiroku.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player18 = Player(name='Hidan', wins=0, loss=0, points=0, img='../static/images/hidan.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player19 = Player(name='Hinata', wins=0, loss=0, points=0, img='../static/images/hinata.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player20 = Player(name='Ino', wins=0, loss=0, points=0,team='Virginia Tech',logo='https://sportslogohistory.com/wp-content/uploads/2018/01/virginia_tech_hokies_1983-pres.png', img='../static/images/ino.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player21 = Player(name='Itachi', wins=0, loss=0, points=0, img='../static/images/itachi.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player22 = Player(name='Jiraiya', wins=0, loss=0, points=0, img='../static/images/jiraiya.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player23 = Player(name='Jutsu Naruto', wins=0, loss=0, points=0, img='../static/images/jutsu.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player24 = Player(name='Juubito', wins=0, loss=0, points=0, img='../static/images/juubito.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player25 = Player(name='Kabuto', wins=0, loss=0, points=0, img='../static/images/kabuto.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player26 = Player(name='Kaguya', wins=0, loss=0, points=0, img='../static/images/kaguya.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player27 = Player(name='Kakashi', wins=0, loss=0, points=0, img='../static/images/regkak.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player28 = Player(name='Kankuro', wins=0, loss=0, points=0, img='../static/images/kankuro.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player29 = Player(name='Karin', wins=0, loss=0, points=0, img='../static/images/karin.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player30 = Player(name='Kiba', wins=0, loss=0, points=0, img='../static/images/kiba.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player31 = Player(name='Killer Bee', wins=0, loss=0, points=0, img='../static/images/killer_bee.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player32 = Player(name='Konan', wins=0, loss=0, points=0, img='../static/images/konan.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player33 = Player(name='Kurama', wins=0, loss=0, points=0, img='../static/images/kurama.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player34 = Player(name='Madara', wins=0, loss=0, points=0, img='../static/images/madara.gif', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player35 = Player(name='Masked Man', wins=0, loss=0, points=0, img='../static/images/tobi.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player36 = Player(name='Massacre Itachi', wins=0, loss=0, points=0, img='../static/images/massacre.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player37 = Player(name='Might Guy', wins=0, loss=0, points=0, img='../static/images/guy.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player38 = Player(name='Minato', wins=0, loss=0, points=0, img='../static/images/minato.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player39 = Player(name='Neji', wins=0, loss=0, points=0, img='../static/images/neji.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player40 = Player(name='Obito', wins=0, loss=0, points=0, img='../static/images/obito.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player41 = Player(name='Orochimaru', wins=0, loss=0, points=0, img='../static/images/orochimaru.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player42 = Player(name='Pain', wins=0, loss=0, points=0, img='../static/images/pain.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player43 = Player(name='Rage Tobi', wins=0, loss=0, points=0, img='../static/images/rage.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player44 = Player(name='Ramen Naruto', wins=0, loss=0, points=0, img='../static/images/ramen.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player45 = Player(name='Rock Lee', wins=0, loss=0, points=0, img='../static/images/rock.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player46 = Player(name='Sage Naruto', wins=0, loss=0, points=0, img='../static/images/sage.gif', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player47 = Player(name='Sai', wins=0, loss=0, points=0, img='../static/images/sai.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player48 = Player(name='Sakura', wins=0, loss=0, points=0, img='../static/images/sakura.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player49 = Player(name='Sasori', wins=0, loss=0, points=0, img='../static/images/sasori.png', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player50 = Player(name='Sasuke', wins=0, loss=0, points=0, img='../static/images/regsas.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player51 = Player(name='Sharingan Kakashi', wins=0, loss=0, points=0, img='../static/images/sharigankak.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player52 = Player(name='Shikamaru', wins=0, loss=0, points=0, img='../static/images/shikamaru.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player53 = Player(name='Shino', wins=0, loss=0, points=0, img='../static/images/shino.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player54 = Player(name='Shukaku', wins=0, loss=0, points=0, img='../static/images/shukaku.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player55 = Player(name='Shuriken Naruto', wins=0, loss=0, points=0, img='../static/images/shuriken.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player56 = Player(name='Six Paths Naruto', wins=0, loss=0, points=0, img='../static/images/six-paths-sage.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player57 = Player(name='Suigetsu', wins=0, loss=0, points=0, img='../static/images/suigetsu.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player58 = Player(name='Sword Sasuke', wins=0, loss=0, points=0, img='../static/images/sword.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player59 = Player(name='Temari', wins=0, loss=0, points=0, img='../static/images/temari.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player60 = Player(name='Tobirama', wins=0, loss=0, points=0, img='../static/images/tobirama.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player61 = Player(name='Tsunade', wins=0, loss=0, points=0, img='../static/images/tsunade.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player62 = Player(name='War Sakura', wins=0, loss=0, points=0, img='../static/images/warsakura.jpeg', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player63 = Player(name='Yamato', wins=0, loss=0, points=0, img='../static/images/yamato.webp', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player64 = Player(name='Zetsu', wins=0, loss=0, points=0, img='../static/images/zetsu.png', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player65 = Player(name='Toji', wins=0, loss=0, points=0, img='https://i0.wp.com/ovicio.com.br/wp-content/uploads/2023/06/20230626-fzgi5egxsainwyd.jpg?resize=555%2C555&ssl=1', gold=0,silver=0,bronze=0,medal=0,badge=0)
    player66 = Player(name='Nanami', wins=0, loss=0, points=0, img='https://64.media.tumblr.com/bee5b4150e08d22f7351d037813cd8b9/13fcef64824dd1b2-da/s1280x1920/f260dbaffb68a41c3554c15561f909841cf1b9dc.jpg', gold=0,silver=0,bronze=0,medal=0,badge=0)




    # db.session.add(res0)
    # db.session.add(res2)
    # db.session.add(res3)
    # db.session.add(res4)
    # db.session.add(res5)
    db.session.add(tour0)
    db.session.add(tour2)
    db.session.add(tour3)
    db.session.add(tour4)
    db.session.add(tour5)
    db.session.add(tour6)
    db.session.add(tour7)
    db.session.add(player1)
    db.session.add(player2)
    db.session.add(player3)
    db.session.add(player4)
    db.session.add(player5)
    #db.session.add(player6)
    #db.session.add(player7)
    db.session.add(player8)
    db.session.add(player9)
    #db.session.add(player10)
    #db.session.add(player11)
    db.session.add(player12)
    db.session.add(player13)
    #db.session.add(player14)
    #db.session.add(player15)
    db.session.add(player16)
    #db.session.add(player17)
    #db.session.add(player18)
    db.session.add(player19)
    db.session.add(player20)
    db.session.add(player21)
    db.session.add(player22)
    #db.session.add(player23)
    db.session.add(player24)
    #db.session.add(player25)
    db.session.add(player26)
    db.session.add(player27)
    db.session.add(player28)
    #db.session.add(player29)
    db.session.add(player30)
    db.session.add(player31)
    db.session.add(player32)
    db.session.add(player33)
    db.session.add(player34)
    #db.session.add(player35)
    #db.session.add(player36)
    db.session.add(player37)
    db.session.add(player38)
    db.session.add(player39)
    db.session.add(player40)
    db.session.add(player41)
    db.session.add(player42)
    db.session.add(player43)
    #db.session.add(player44)
    db.session.add(player45)
    db.session.add(player46)
    db.session.add(player47)
    db.session.add(player48)
    db.session.add(player49)
    db.session.add(player50)
    #db.session.add(player51)
    db.session.add(player52)
    db.session.add(player53)
    db.session.add(player54)
    #db.session.add(player55)
    db.session.add(player56)
    db.session.add(player57)
    #db.session.add(player58)
    db.session.add(player59)
    db.session.add(player60)
    db.session.add(player61)
    #db.session.add(player62)
    db.session.add(player63)
    #db.session.add(player64)
    db.session.add(player65)
    db.session.add(player66)
    db.session.commit()
    print('All Players created!')

    # Player.query.delete()  # Deletes all rows in the table
    # Result.query.delete()
    # Opponent.query.delete()
    # Tour.query.delete()
    # db.session.commit()
    # print("Database cleared.")
