"""Added team conf column

Revision ID: 02716700a56b
Revises: b602ce0fbe18
Create Date: 2025-12-27 15:47:27.840735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02716700a56b'
down_revision = 'b602ce0fbe18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('conf', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'conf')
    # ### end Alembic commands ###
