"""Added dual_points column

Revision ID: 0945a017823c
Revises: 1a599d93c2fc
Create Date: 2025-05-15 01:46:38.813305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0945a017823c'
down_revision = '1a599d93c2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('dual_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'dual_points')
    # ### end Alembic commands ###
