"""season 2 foundation fields

Revision ID: 0d19975bf2b2
Revises: 2f82255fd96c
Create Date: 2026-06-17 12:49:45.132702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d19975bf2b2'
down_revision = '2f82255fd96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_team_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('player_season_stats', sa.Column('wood', sa.Integer(), nullable=True))
    op.add_column('player_season_stats', sa.Column('ribbon', sa.Integer(), nullable=True))
    op.add_column('player_season_stats', sa.Column('blood', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_season_stats', 'blood')
    op.drop_column('player_season_stats', 'ribbon')
    op.drop_column('player_season_stats', 'wood')
    op.drop_table('tournament_team_scores')
    # ### end Alembic commands ###
