"""Added tour_points column

Revision ID: 15fa5b01d58f
Revises: 7ebe62f94a71
Create Date: 2026-06-09 20:42:57.982225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fa5b01d58f'
down_revision = '7ebe62f94a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_pick', sa.Column('match_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_pick', 'match_id')
    # ### end Alembic commands ###
