"""Added dual winnerId

Revision ID: 1a599d93c2fc
Revises: b6efc992f3f8
Create Date: 2025-05-14 23:52:26.421079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a599d93c2fc'
down_revision = 'b6efc992f3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dual', sa.Column('winnerId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dual', 'winnerId')
    # ### end Alembic commands ###
