"""Added tour_points column

Revision ID: 30fababb2662
Revises: 8dfe1b6f9948
Create Date: 2025-03-24 20:30:12.162563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fababb2662'
down_revision = '8dfe1b6f9948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('tour_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'tour_points')
    # ### end Alembic commands ###
