"""Add logo and team columns to Player table

Revision ID: 33efcd499e88
Revises: 8fb7b76a5798
Create Date: 2024-12-31 21:47:33.633639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33efcd499e88'
down_revision = '8fb7b76a5798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('team', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'logo')
    op.drop_column('players', 'team')
    # ### end Alembic commands ###
