"""Recreate team roster season with nullable position

Revision ID: 350657b48401
Revises: fdd186c80d80
Create Date: 2026-06-10 12:24:40.350049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350657b48401'
down_revision = 'fdd186c80d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_roster_season')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_roster_season',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('season_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.VARCHAR(), nullable=False),
    sa.Column('team_name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
