"""Added tour week and finalized col

Revision ID: 3a79e3d6945f
Revises: 869bd4e8fbd6
Create Date: 2026-06-17 14:24:34.858000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a79e3d6945f'
down_revision = '869bd4e8fbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('tours', sa.Column('finalized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'finalized')
    op.drop_column('tours', 'week')
    # ### end Alembic commands ###
