"""Added bonus percent column

Revision ID: 3f1b5a57a1de
Revises: 9a59491c4bc1
Create Date: 2025-04-04 17:00:05.736516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1b5a57a1de'
down_revision = '9a59491c4bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('bonus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'bonus')
    # ### end Alembic commands ###
