"""Added tour_points column

Revision ID: 4369d9af25da
Revises: b231536bf87f
Create Date: 2025-05-04 17:52:51.332819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4369d9af25da'
down_revision = 'b231536bf87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('tour_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'tour_points')
    # ### end Alembic commands ###
