"""Add score column to Battle table

Revision ID: 438fba8814b5
Revises: 33efcd499e88
Create Date: 2024-12-31 22:35:00.141024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438fba8814b5'
down_revision = '33efcd499e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('opponent', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opponent', 'score')
    op.drop_column('battle', 'score')
    # ### end Alembic commands ###
