"""added player of the day

Revision ID: 46ea9fc3cba0
Revises: bc10ef460fd9
Create Date: 2026-06-09 21:03:12.222276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ea9fc3cba0'
down_revision = 'bc10ef460fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_of_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_date', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pick_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_of_day')
    # ### end Alembic commands ###
