"""Added height

Revision ID: 497c4edc8b69
Revises: bdd18921203a
Create Date: 2026-06-16 02:22:07.433750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497c4edc8b69'
down_revision = 'bdd18921203a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('height', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'height')
    # ### end Alembic commands ###
