"""Added date columns

Revision ID: 4ffa733e085b
Revises: 621c171666b1
Create Date: 2026-06-03 20:49:43.813264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffa733e085b'
down_revision = '621c171666b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dual', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('opponent', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opponent', 'date')
    op.drop_column('dual', 'date')
    # ### end Alembic commands ###
