"""add res name

Revision ID: 59a4302d65fb
Revises: 497c4edc8b69
Create Date: 2026-06-16 03:23:22.299785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a4302d65fb'
down_revision = '497c4edc8b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('tour_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'tour_name')
    # ### end Alembic commands ###
