"""Added tour_points column

Revision ID: 621c171666b1
Revises: f20909bd531d
Create Date: 2026-04-18 13:41:51.221366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621c171666b1'
down_revision = 'f20909bd531d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_score', sa.Column('sh', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_score', 'sh')
    # ### end Alembic commands ###
