"""Updated rank history model

Revision ID: 6f941429dc7e
Revises: 3f1b5a57a1de
Create Date: 2025-04-06 19:03:43.694140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f941429dc7e'
down_revision = '3f1b5a57a1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourId', sa.Integer(), nullable=True),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rank_history')
    # ### end Alembic commands ###
