"""Added team_rank_hist_points column

Revision ID: 718acb42a6df
Revises: 02716700a56b
Create Date: 2026-01-05 18:41:08.508981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718acb42a6df'
down_revision = '02716700a56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_rank_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_rank_history')
    # ### end Alembic commands ###
