"""Added tour_points column

Revision ID: 7ebe62f94a71
Revises: c87151d0c1ba
Create Date: 2026-06-09 20:29:14.081726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebe62f94a71'
down_revision = 'c87151d0c1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_date', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pick_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_pick')
    # ### end Alembic commands ###
