"""Updated Battle model

Revision ID: 82c70e0efd7c
Revises: d669b2789b74
Create Date: 2025-01-30 14:01:20.741413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c70e0efd7c'
down_revision = 'd669b2789b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('psu', sa.Integer(), nullable=True),
    sa.Column('tosu', sa.Integer(), nullable=True),
    sa.Column('okla', sa.Integer(), nullable=True),
    sa.Column('corn', sa.Integer(), nullable=True),
    sa.Column('leh', sa.Integer(), nullable=True),
    sa.Column('nc', sa.Integer(), nullable=True),
    sa.Column('iowa', sa.Integer(), nullable=True),
    sa.Column('isu', sa.Integer(), nullable=True),
    sa.Column('minn', sa.Integer(), nullable=True),
    sa.Column('vt', sa.Integer(), nullable=True),
    sa.Column('mizz', sa.Integer(), nullable=True),
    sa.Column('neb', sa.Integer(), nullable=True),
    sa.Column('stan', sa.Integer(), nullable=True),
    sa.Column('mich', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_score')
    # ### end Alembic commands ###
