"""Added tour_points column

Revision ID: 8ac72b8bc6e7
Revises: 718acb42a6df
Create Date: 2026-02-20 17:42:03.953647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac72b8bc6e7'
down_revision = '718acb42a6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_score', sa.Column('Colorado', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_score', 'Colorado')
    # ### end Alembic commands ###
