"""Updated Battle model

Revision ID: 8dfe1b6f9948
Revises: a79822aaf5eb
Create Date: 2025-01-31 17:35:10.363006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfe1b6f9948'
down_revision = 'a79822aaf5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourId', sa.Integer(), nullable=True),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_team')
    # ### end Alembic commands ###
