"""initial migration

Revision ID: 8fb7b76a5798
Revises: 
Create Date: 2024-11-12 15:47:12.906887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb7b76a5798'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_1', sa.String(), nullable=True),
    sa.Column('victory_1', sa.Boolean(), nullable=True),
    sa.Column('player_2', sa.Integer(), nullable=True),
    sa.Column('victory_2', sa.Boolean(), nullable=True),
    sa.Column('tour_name', sa.Integer(), nullable=True),
    sa.Column('round', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opponent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('victory', sa.Boolean(), nullable=True),
    sa.Column('tour_name', sa.Integer(), nullable=True),
    sa.Column('round', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('silver', sa.Integer(), nullable=True),
    sa.Column('bronze', sa.Integer(), nullable=True),
    sa.Column('medal', sa.Integer(), nullable=True),
    sa.Column('badge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=255), nullable=False),
    sa.Column('second', sa.String(length=255), nullable=False),
    sa.Column('third', sa.String(length=255), nullable=False),
    sa.Column('fourth', sa.String(length=255), nullable=False),
    sa.Column('fifth', sa.String(length=255), nullable=False),
    sa.Column('sixth', sa.String(length=255), nullable=False),
    sa.Column('seventh', sa.String(length=255), nullable=False),
    sa.Column('eigth', sa.String(length=255), nullable=False),
    sa.Column('ninth', sa.String(length=255), nullable=False),
    sa.Column('tenth', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('first', sa.String(length=50), nullable=False),
    sa.Column('second', sa.String(length=50), nullable=False),
    sa.Column('third', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tours')
    op.drop_table('results')
    op.drop_table('players')
    op.drop_table('opponent')
    op.drop_table('battle')
    # ### end Alembic commands ###
