"""Updated tour model

Revision ID: 8fc37128f24d
Revises: 999a2f9e9385
Create Date: 2025-01-12 12:55:36.090110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc37128f24d'
down_revision = '999a2f9e9385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('thirtenth', sa.String(length=255), nullable=True))
    op.add_column('results', sa.Column('fourtenth', sa.String(length=255), nullable=True))
    op.add_column('results', sa.Column('fifthtenth', sa.String(length=255), nullable=True))
    op.add_column('results', sa.Column('sixtenth', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'sixtenth')
    op.drop_column('results', 'fifthtenth')
    op.drop_column('results', 'fourtenth')
    op.drop_column('results', 'thirtenth')
    # ### end Alembic commands ###
