"""Add eleventh and twelfth columns to results

Revision ID: 999a2f9e9385
Revises: a3bc6cd6edb4
Create Date: 2025-01-01 22:01:23.491076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999a2f9e9385'
down_revision = 'a3bc6cd6edb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('eleventh', sa.String(length=255), nullable=True))
    op.add_column('results', sa.Column('twelfth', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'twelfth')
    op.drop_column('results', 'eleventh')
    # ### end Alembic commands ###
