"""Added rank column

Revision ID: 9a59491c4bc1
Revises: ac6b303de2fe
Create Date: 2025-04-03 12:27:51.067546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a59491c4bc1'
down_revision = 'ac6b303de2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'rank')
    # ### end Alembic commands ###
