"""Added to rankhist season id

Revision ID: 9e7a2410d9e2
Revises: 32a1eaa036e6
Create Date: 2026-06-10 12:33:44.222353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7a2410d9e2'
down_revision = '32a1eaa036e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank_history', sa.Column('season_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rank_history', 'season_id')
    # ### end Alembic commands ###
