"""Add new columns to table

Revision ID: a3bc6cd6edb4
Revises: 9ed49bb30271
Create Date: 2025-01-01 21:24:57.315496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bc6cd6edb4'
down_revision = '9ed49bb30271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('eleventh', sa.String(length=255), nullable=False))
    op.add_column('results', sa.Column('twelfth', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'twelfth')
    op.drop_column('results', 'eleventh')
    # ### end Alembic commands ###
