"""Added classic fight boolean

Revision ID: a458b6276561
Revises: 59a4302d65fb
Create Date: 2026-06-16 12:01:18.284130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a458b6276561'
down_revision = '59a4302d65fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opponent', sa.Column('is_ressist', sa.Boolean(), nullable=True))
    op.add_column('opponent', sa.Column('fotn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opponent', 'fotn')
    op.drop_column('opponent', 'is_ressist')
    # ### end Alembic commands ###
