"""added elo

Revision ID: a6a0a20d5b20
Revises: 3a79e3d6945f
Create Date: 2026-06-17 23:44:08.147805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a0a20d5b20'
down_revision = '3a79e3d6945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('elo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('player_season_stats', sa.Column('elo', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('peak_elo', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_season_stats', 'peak_elo')
    op.drop_column('player_season_stats', 'elo')
    op.drop_table('elo_history')
    # ### end Alembic commands ###
