"""Updated Battle model

Revision ID: a79822aaf5eb
Revises: b2f8d43e26a8
Create Date: 2025-01-30 14:09:44.910120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79822aaf5eb'
down_revision = 'b2f8d43e26a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_score', sa.Column('osu', sa.Integer(), nullable=True))
    op.add_column('tour_score', sa.Column('okst', sa.Integer(), nullable=True))
    op.add_column('tour_score', sa.Column('ncst', sa.Integer(), nullable=True))
    op.drop_column('tour_score', 'okla')
    op.drop_column('tour_score', 'nc')
    op.drop_column('tour_score', 'tosu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_score', sa.Column('tosu', sa.INTEGER(), nullable=True))
    op.add_column('tour_score', sa.Column('nc', sa.INTEGER(), nullable=True))
    op.add_column('tour_score', sa.Column('okla', sa.INTEGER(), nullable=True))
    op.drop_column('tour_score', 'ncst')
    op.drop_column('tour_score', 'okst')
    op.drop_column('tour_score', 'osu')
    # ### end Alembic commands ###
