"""Added team rank column

Revision ID: aa2b692f916d
Revises: 0945a017823c
Create Date: 2025-05-30 13:16:23.867055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2b692f916d'
down_revision = '0945a017823c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'rank')
    # ### end Alembic commands ###
