"""added tour wins

Revision ID: ac6b303de2fe
Revises: 30fababb2662
Create Date: 2025-03-25 19:29:02.787893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6b303de2fe'
down_revision = '30fababb2662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_team', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('tour_team', sa.Column('loss', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_team', 'loss')
    op.drop_column('tour_team', 'wins')
    # ### end Alembic commands ###
