"""Added rank history total col

Revision ID: b231536bf87f
Revises: 6f941429dc7e
Create Date: 2025-05-03 16:23:37.634000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b231536bf87f'
down_revision = '6f941429dc7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank_history', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rank_history', 'total')
    # ### end Alembic commands ###
