"""Updated Battle model

Revision ID: b2f8d43e26a8
Revises: 82c70e0efd7c
Create Date: 2025-01-30 14:03:33.693070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f8d43e26a8'
down_revision = '82c70e0efd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'first')
    op.drop_column('tours', 'second')
    op.drop_column('tours', 'third')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('third', sa.VARCHAR(length=50), nullable=False))
    op.add_column('tours', sa.Column('second', sa.VARCHAR(length=50), nullable=False))
    op.add_column('tours', sa.Column('first', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
