"""added deal wins

Revision ID: b602ce0fbe18
Revises: 54ae1b16ae0d
Create Date: 2025-05-31 14:23:46.649524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b602ce0fbe18'
down_revision = '54ae1b16ae0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('d_wins', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('d_loss', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'd_loss')
    op.drop_column('players', 'd_wins')
    # ### end Alembic commands ###
