"""Added status to fighters

Revision ID: b6efc992f3f8
Revises: 4369d9af25da
Create Date: 2025-05-04 21:33:07.361651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6efc992f3f8'
down_revision = '4369d9af25da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_team', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_team', 'status')
    # ### end Alembic commands ###
