"""clean check

Revision ID: bc10ef460fd9
Revises: 15fa5b01d58f
Create Date: 2026-06-09 20:55:23.425680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc10ef460fd9'
down_revision = '15fa5b01d58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_pick')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_pick',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pick_date', sa.VARCHAR(length=20), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pick_date')
    )
    # ### end Alembic commands ###
