"""Added tour_points column

Revision ID: bdd18921203a
Revises: 7a7e2bfefb3c
Create Date: 2026-06-14 00:34:32.880082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd18921203a'
down_revision = '7a7e2bfefb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'active')
    # ### end Alembic commands ###
