"""Added tour_points column

Revision ID: c87151d0c1ba
Revises: 4ffa733e085b
Create Date: 2026-06-09 15:42:19.425938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87151d0c1ba'
down_revision = '4ffa733e085b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birthday', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'birthday')
    # ### end Alembic commands ###
