"""added team

Revision ID: d669b2789b74
Revises: d6e30f84c08d
Create Date: 2025-01-21 20:17:16.646243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd669b2789b74'
down_revision = 'd6e30f84c08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dual', sa.Column('hscore', sa.Integer(), nullable=True))
    op.add_column('dual', sa.Column('ascore', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dual', 'ascore')
    op.drop_column('dual', 'hscore')
    op.drop_table('team')
    # ### end Alembic commands ###
