"""Updated Dual model

Revision ID: d6e30f84c08d
Revises: 8fc37128f24d
Create Date: 2025-01-16 22:48:58.079723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e30f84c08d'
down_revision = '8fc37128f24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('away', sa.String(), nullable=True),
    sa.Column('week', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dual')
    # ### end Alembic commands ###
