"""Added tour_points column

Revision ID: f20909bd531d
Revises: 8ac72b8bc6e7
Create Date: 2026-02-20 18:02:21.320152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20909bd531d'
down_revision = '8ac72b8bc6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_score', sa.Column('Northern_Iowa', sa.Integer(), nullable=True))
    op.add_column('tour_score', sa.Column('Wyoming', sa.Integer(), nullable=True))
    op.add_column('tour_score', sa.Column('Arizona_State', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_score', 'Arizona_State')
    op.drop_column('tour_score', 'Wyoming')
    op.drop_column('tour_score', 'Northern_Iowa')
    # ### end Alembic commands ###
