"""Add season support

Revision ID: fdd186c80d80
Revises: 46ea9fc3cba0
Create Date: 2026-06-10 12:13:09.411407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd186c80d80'
down_revision = '46ea9fc3cba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('d_wins', sa.Integer(), nullable=True),
    sa.Column('d_loss', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('tour_points', sa.Integer(), nullable=True),
    sa.Column('dual_points', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('pos_rank', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('silver', sa.Integer(), nullable=True),
    sa.Column('bronze', sa.Integer(), nullable=True),
    sa.Column('medal', sa.Integer(), nullable=True),
    sa.Column('badge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_roster_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('tour_points', sa.Integer(), nullable=True),
    sa.Column('vanguard', sa.Integer(), nullable=True),
    sa.Column('guard', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dual', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('opponent', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('position', sa.String(), nullable=True))
    op.add_column('players', sa.Column('pos_rank', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('divison', sa.String(), nullable=True))
    op.add_column('team', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('team_rank', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('team_rank_history', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('tour_score', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('tour_team', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('tours', sa.Column('season_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'season_id')
    op.drop_column('tour_team', 'season_id')
    op.drop_column('tour_score', 'season_id')
    op.drop_column('team_rank_history', 'season_id')
    op.drop_column('team_rank', 'season_id')
    op.drop_column('team', 'season_id')
    op.drop_column('team', 'divison')
    op.drop_column('results', 'season_id')
    op.drop_column('players', 'pos_rank')
    op.drop_column('players', 'position')
    op.drop_column('opponent', 'season_id')
    op.drop_column('dual', 'season_id')
    op.drop_table('team_season_stats')
    op.drop_table('team_roster_season')
    op.drop_table('seasons')
    op.drop_table('player_season_stats')
    # ### end Alembic commands ###
